### ISSUE TITLE
issue running mutli-unet model on neptune.ml

### ISSUE THREAD

**Issue by mpsampat** [neptune-ml/data-science-bowl-2018#55]
I did a git pull on master and run this: 
$ neptune login
$ neptune send main.py --worker gcp-gpu-large --environment pytorch-0.2.0-gpu-py3 -- train_evaluate_predict_pipeline --pipeline_name unet_multitask

but then i get this errors. (they are reproducible)
File "/neptune/callbacks.py", line 71, in get_prediction_masks
--
210.42965 | prediction = sigmoid(np.squeeze(outputs_batch.data.cpu().numpy(), axis=1))
210.429778 | AttributeError: 'list' object has no attribute 'data'
Any suggestions to fix them ? 
thanks
Mehul

There are couple of things that will make the processing of your issue faster:
1. Use labels to categorize your issue,
2. Make sure that you are using the latest version of the master branch of data-science-bowl-2018,
3. In case it is a bug issue, it would be nice to provide more technical details or python script that reproduces your error.

Thanks!

Neptune's ml-team

**Comment by szhitansky** [comment]
Hello, 

I've got similar error for unet_multitask, fresh Ubuntu 16.04, Anaconda 5.0.1. 
Latest Master sources, generic pipeline and default yaml config:

- git clone https://github.com/neptune-ml/data-science-bowl-2018
- pip install -r requirements.txt
- neptune run main.py -- prepare_metadata
- neptune run main.py -- prepare_masks
- neptune send main.py --worker gcp-gpu-large --environment pytorch-0.2.0-gpu-py3 -- train_evaluate_predict_pipeline --pipeline_name unet_multitask

BTW, same error for Local run and for NepruneML environments.

**Comment by szhitansky** [comment]
Forgot to add, it's right after epoch 0:

```
411.606309	2018-03-19 14-36-13 steps >>> epoch 0 mask: 0.59421
411.606645	2018-03-19 14-36-13 steps >>> epoch 0 contour: 0.78396
411.606822	2018-03-19 14-36-13 steps >>> epoch 0 center: 0.16617
411.606957	2018-03-19 14-36-13 steps >>> epoch 0 sum: 1.54435
433.548634	2018-03-19 14-36-35 steps >>> epoch 0 validation mask: 0.47229
433.548903	2018-03-19 14-36-35 steps >>> epoch 0 validation contour: 0.72395
433.549047	2018-03-19 14-36-35 steps >>> epoch 0 validation center: 0.17359
433.549192	2018-03-19 14-36-35 steps >>> epoch 0 validation sum: 1.36984
455.55704	2018-03-19 14-36-57 steps >>> epoch 1 current lr: 0.0001
```
```

478.358481 | File "main.py", line 154, in train_evaluate_predict_pipeline
478.358608 | _train_pipeline(pipeline_name, validation_size)
478.358726 | File "main.py", line 81, in _train_pipeline
478.358844 | pipeline.fit_transform(data)
478.358966 | File "/neptune/steps/base.py", line 92, in fit_transform
478.359104 | step_inputs[input_step.name] = input_step.fit_transform(data)
478.359225 | File "/neptune/steps/base.py", line 92, in fit_transform
478.359343 | step_inputs[input_step.name] = input_step.fit_transform(data)
478.359534 | File "/neptune/steps/base.py", line 92, in fit_transform
478.359654 | step_inputs[input_step.name] = input_step.fit_transform(data)
478.359772 | File "/neptune/steps/base.py", line 98, in fit_transform
478.35989 | step_output_data = self._cached_fit_transform(step_inputs)
478.3601 | File "/neptune/steps/base.py", line 109, in _cached_fit_transform
478.360289 | step_output_data = self.transformer.fit_transform(**step_inputs)
478.360408 | File "/neptune/steps/base.py", line 241, in fit_transform
478.360534 | self.fit(*args, **kwargs)
478.360658 | File "/neptune/steps/pytorch/models.py", line 67, in fit
478.360864 | self.callbacks.on_epoch_end()
478.360997 | File "/neptune/steps/pytorch/callbacks.py", line 86, in on_epoch_end
478.361124 | callback.on_epoch_end(*args, **kwargs)
478.36125 | File "/neptune/callbacks.py", line 20, in on_epoch_end
478.361391 | self._send_image_channels()
478.361522 | File "/neptune/callbacks.py", line 25, in _send_image_channels
478.361647 | pred_masks = self.get_prediction_masks()
478.36178 | File "/neptune/callbacks.py", line 71, in get_prediction_masks
478.361904 | prediction = sigmoid(np.squeeze(outputs_batch.data.cpu().numpy(), axis=1))
478.362027 | AttributeError: 'list' object has no attribute 'data'
```

**Comment by mpsampat** [comment]
Yes I got the exact same error message after epoch 0 on Neptune.ml

**Comment by kamil-kaczmarek** [comment]
Hey @szhitansky @mpsampat, thank you. I am looking at this right now. I will let you know, when fixed.

**Comment by kamil-kaczmarek** [comment]
@jakubczakon @szhitansky @mpsampat It is fixed and merged to `master` in #58.

@szhitansky when you start your experiment using `neptune send ...` you do not need to execute these two commands:
```bash
neptune run main.py -- prepare_metadata
neptune run main.py -- prepare_masks
```
However, they are necessary when starting experiment with `neptune run ...`

Finally, take a look at the [models.py:L38](https://github.com/neptune-ml/data-science-bowl-2018/blob/master/models.py#L38). Manipulate loss function weights -> we think that masks and contour are most important. More info on [Solution 4](https://github.com/neptune-ml/data-science-bowl-2018/wiki/UNet-with-weighted-loss-and-morphological-postprocessing) wiki page.

Best,
Kamil

**Comment by szhitansky** [comment]
@kamil-kaczmarek thanks for your efforts but I still have this error for local run and for neptune.ml

**Comment by kamil-kaczmarek** [comment]
Hi @szhitansky I was typo error in the [neptune.yaml](https://github.com/neptune-ml/data-science-bowl-2018/blob/master/neptune.yaml#L55). It was `nr_unet_outputs: 3` -> should be 4.

**Comment by szhitansky** [comment]
@kamil-kaczmarek many thanks, issue was resolved.

**Comment by kamil-kaczmarek** [comment]
@szhitansky nice!
